In [2]:
def function(x):
    return 5+x
function(6)

11

In [32]:
import pandas as pd
import os
import numpy as np

In [9]:
os.getcwd()

'C:\\Users\\admin\\Documents'

In [12]:
df = pd.read_csv("CLI data.csv")

In [13]:
df

,Rank,City,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex
0,1,"Zurich, Switzerland",149.53,66.76,163.71,140.58,126.30
1,2,"Hamilton, Bermuda",148.13,117.80,145.20,152.54,93.42
2,3,"Zug, Switzerland",142.54,67.39,148.36,143.18,105.62
3,4,"Geneva, Switzerland",142.12,70.25,147.13,138.96,115.20
4,5,"Basel, Switzerland",142.02,51.54,149.54,131.72,113.13
5,6,"Bern, Switzerland",135.51,45.33,145.72,122.48,101.65
6,7,"Lausanne, Switzerland",131.38,54.56,136.95,127.87,112.33
7,8,"Reykjavik, Iceland",130.73,55.90,128.37,140.61,68.49
8,9,"Lugano, Switzerland",124.39,51.73,120.83,127.53,108.92
9,10,"Stavanger, Norway",116.98,37.40,107.72,142.61,101.00
10,11,"Trondheim, Norway",116.02,41.27,110.10,128.03,93.68
11,12,"Oslo, Norway",114.78,47.99,111.48,126.20,86.67
12,13,"Bergen, Norway",112.66,39.58,106.84,117.45,87.68
13,14,"Nassau, Bahamas",109.58,37.40,103.09,99.27,43.82
14,15,"Honolulu, HI, United States",103.32,64.98,121.83,88.49,84.93
15,16,"San Francisco, CA, United States",101.94,119.63,116.73,93.57,104.40
16,17,"Anchorage, AK, United States",101.90,41.57,109.58,88.67,130.22
17,18,"Brooklyn, NY, United States",101.06,77.52,105.51,106.84,82.64
18,19,"New York, NY, United States",100.00,100.00,100.00,100.00,100.00
19,20,"Rockville, MD, United States",98.81,61.40,97.20,71.68,135.58
20,21,"Tokyo, Japan",97.71,38.68,107.25,57.87,93.49
21,22,"Copenhagen, Denmark",97.14,49.61,78.25,113.91,93.39
22,23,"Washington, DC, United States",95.96,74.32,96.97,90.78,107.86
23,24,"New Haven, CT, United States",94.10,47.09,112.78,91.54,114.53
24,25,"Berkeley, CA, United States",93.86,76.36,109.86,81.71,87.37
25,26,"Seattle, WA, United States",93.31,65.46,98.17,86.72,121.29
26,27,"Arlington, VA, United States",93.17,67.79,93.16,85.61,117.45
27,28,"Aalborg, Denmark",92.12,25.34,77.34,104.60,89.90
28,29,"Tel Aviv-Yafo, Israel",92.09,49.51,80.75,96.79,93.00
29,30,"Santa Rosa, CA, United States",91.92,55.04,97.22,78.70,116.21
...,...,...,...,...,...,...,...
481,482,"Bangalore, India",30.24,9.41,32.95,19.57,86.79
482,483,"Tunis, Tunisia",29.93,6.51,28.94,20.42,32.94
483,484,"Thane, India",29.83,8.51,31.74,20.03,51.96
484,485,"Navi Mumbai, India",29.41,9.72,31.29,20.53,73.30
485,486,"Pristina, Kosovo (Disputed Territory)",29.40,8.90,26.65,22.28,52.71
486,487,"Karachi, Pakistan",29.11,7.48,29.16,21.44,35.72
487,488,"Ahmedabad, India",28.95,6.65,31.25,21.09,57.06
488,489,"Chandigarh, India",28.94,6.31,30.74,19.97,64.70
489,490,"Chennai, India",28.78,7.09,31.45,18.75,71.99
490,491,"Goa, India",28.52,7.57,30.98,20.94,49.66
491,492,"Surat, India",28.47,4.50,30.17,21.43,55.55
492,493,"Kolkata, India",28.28,6.97,29.91,22.74,47.99
493,494,"Dnipropetrovsk, Ukraine",28.09,7.13,22.74,20.69,31.03
494,495,"Lucknow (Lakhnau), India",28.07,4.60,29.00,18.03,53.68
495,496,"Jaipur, India",27.92,4.62,29.81,16.61,65.05
496,497,"Kharkiv, Ukraine",27.85,9.94,22.03,19.26,22.54
497,498,"Vadodara, India",27.31,3.85,31.50,16.06,67.23
498,499,"Nagpur, India",27.18,4.86,29.35,19.34,68.56
499,500,"Indore, India",27.01,4.28,26.64,16.98,44.20
500,501,"Lviv, Ukraine",26.97,8.48,22.66,17.35,22.69
501,502,"Hyderabad, India",26.87,6.20,28.95,17.66,65.47
502,503,"Mysore, India",26.23,4.52,32.03,13.28,35.53
503,504,"Cairo, Egypt",26.19,5.14,23.30,22.47,23.96
504,505,"Visakhapatnam, India",25.57,5.14,28.40,16.13,53.78
505,506,"Kochi, India",25.40,6.18,28.26,14.41,60.04
506,507,"Bhubaneswar, India",25.24,4.57,28.87,14.71,52.38
507,508,"Coimbatore, India",24.83,5.61,26.31,15.29,47.01
508,509,"Alexandria, Egypt",24.54,5.09,23.50,17.66,21.42
509,510,"Mangalore, India",23.17,5.68,23.88,12.61,95.97
510,511,"Thiruvananthapuram, India",21.75,5.17,23.72,12.12,62.76

In [14]:
df.head()

,Rank,City,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex
0,1,"Zurich, Switzerland",149.53,66.76,163.71,140.58,126.30
1,2,"Hamilton, Bermuda",148.13,117.80,145.20,152.54,93.42
2,3,"Zug, Switzerland",142.54,67.39,148.36,143.18,105.62
3,4,"Geneva, Switzerland",142.12,70.25,147.13,138.96,115.20
4,5,"Basel, Switzerland",142.02,51.54,149.54,131.72,113.13

In [16]:
df.shape

(511, 7)

In [17]:
df.columns

Index(['Rank', 'City', 'CostofLivingIndex', 'RentIndex', 'GroceriesIndex',
       'RestaurantPriceIndex', 'LocalPurchasingPowerIndex'],
      dtype='object')

In [18]:
df.describe()

,Rank,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex
count,511.000000,511.000000,511.000000,511.000000,511.000000,511.000000
mean,256.000000,65.177691,26.765793,63.414697,58.992524,79.989687
std,147.657261,22.371029,17.651107,24.380114,26.669124,33.742696
min,1.000000,21.750000,3.130000,22.030000,12.120000,2.960000
25%,128.500000,45.740000,12.975000,42.460000,33.325000,51.285000
50%,256.000000,70.640000,24.540000,64.980000,65.370000,84.160000
75%,383.500000,79.765000,34.440000,80.460000,78.175000,104.555000
max,511.000000,149.530000,119.630000,163.710000,152.540000,176.220000

In [21]:
df.City.value_counts()

Dar Es Salaam, Tanzania                1
Limerick, Ireland                      1
Indore, India                          1
Chandigarh, India                      1
Wellington, New Zealand                1
Noida, India                           1
Madrid, Spain                          1
Porto, Portugal                        1
Dayton, OH, United States              1
Antwerp, Belgium                       1
Moncton, Canada                        1
Hobart, Australia                      1
Ahmedabad, India                       1
Haifa, Israel                          1
Doha, Qatar                            1
Lethbridge, AB, Canada                 1
Ann Arbor, MI, United States           1
Gainesville, FL, United States         1
Barcelona, Spain                       1
Allentown, PA, United States           1
Tampere, Finland                       1
Algiers, Algeria                       1
Kitchener, Canada                      1
Gold Coast, Australia                  1
Sharjah, United Arab Emirates          1
Oxford, United Kingdom                 1
San Salvador, El Salvador              1
Guangzhou, China                       1
Newcastle Upon Tyne, United Kingdom    1
Hartford, CT, United States            1
                                      ..
Coimbatore, India                      1
Manama, Bahrain                        1
Beijing, China                         1
Cordoba, Argentina                     1
Athens, Greece                         1
Riga, Latvia                           1
Nuremberg, Germany                     1
Rabat, Morocco                         1
Reading, United Kingdom                1
Gothenburg, Sweden                     1
Dhaka, Bangladesh                      1
Bratislava, Slovakia                   1
Santiago, Chile                        1
Adelaide, Australia                    1
Cancun, Mexico                         1
Copenhagen, Denmark                    1
Las Vegas, NV, United States           1
Singapore, Singapore                   1
Kota Kinabalu, Malaysia                1
Mexico City, Mexico                    1
Melbourne, Australia                   1
Birmingham, United Kingdom             1
Santo Domingo, Dominican Republic      1
Tulsa, OK, United States               1
Hamilton, Canada                       1
Houston, TX, United States             1
Pittsburgh, PA, United States          1
Thiruvananthapuram, India              1
Durham, NC, United States              1
Bonn, Germany                          1
Name: City, dtype: int64

In [24]:
df.rename(columns={"City":"Place"})

,Rank,Place,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex
0,1,"Zurich, Switzerland",149.53,66.76,163.71,140.58,126.30
1,2,"Hamilton, Bermuda",148.13,117.80,145.20,152.54,93.42
2,3,"Zug, Switzerland",142.54,67.39,148.36,143.18,105.62
3,4,"Geneva, Switzerland",142.12,70.25,147.13,138.96,115.20
4,5,"Basel, Switzerland",142.02,51.54,149.54,131.72,113.13
5,6,"Bern, Switzerland",135.51,45.33,145.72,122.48,101.65
6,7,"Lausanne, Switzerland",131.38,54.56,136.95,127.87,112.33
7,8,"Reykjavik, Iceland",130.73,55.90,128.37,140.61,68.49
8,9,"Lugano, Switzerland",124.39,51.73,120.83,127.53,108.92
9,10,"Stavanger, Norway",116.98,37.40,107.72,142.61,101.00
10,11,"Trondheim, Norway",116.02,41.27,110.10,128.03,93.68
11,12,"Oslo, Norway",114.78,47.99,111.48,126.20,86.67
12,13,"Bergen, Norway",112.66,39.58,106.84,117.45,87.68
13,14,"Nassau, Bahamas",109.58,37.40,103.09,99.27,43.82
14,15,"Honolulu, HI, United States",103.32,64.98,121.83,88.49,84.93
15,16,"San Francisco, CA, United States",101.94,119.63,116.73,93.57,104.40
16,17,"Anchorage, AK, United States",101.90,41.57,109.58,88.67,130.22
17,18,"Brooklyn, NY, United States",101.06,77.52,105.51,106.84,82.64
18,19,"New York, NY, United States",100.00,100.00,100.00,100.00,100.00
19,20,"Rockville, MD, United States",98.81,61.40,97.20,71.68,135.58
20,21,"Tokyo, Japan",97.71,38.68,107.25,57.87,93.49
21,22,"Copenhagen, Denmark",97.14,49.61,78.25,113.91,93.39
22,23,"Washington, DC, United States",95.96,74.32,96.97,90.78,107.86
23,24,"New Haven, CT, United States",94.10,47.09,112.78,91.54,114.53
24,25,"Berkeley, CA, United States",93.86,76.36,109.86,81.71,87.37
25,26,"Seattle, WA, United States",93.31,65.46,98.17,86.72,121.29
26,27,"Arlington, VA, United States",93.17,67.79,93.16,85.61,117.45
27,28,"Aalborg, Denmark",92.12,25.34,77.34,104.60,89.90
28,29,"Tel Aviv-Yafo, Israel",92.09,49.51,80.75,96.79,93.00
29,30,"Santa Rosa, CA, United States",91.92,55.04,97.22,78.70,116.21
...,...,...,...,...,...,...,...
481,482,"Bangalore, India",30.24,9.41,32.95,19.57,86.79
482,483,"Tunis, Tunisia",29.93,6.51,28.94,20.42,32.94
483,484,"Thane, India",29.83,8.51,31.74,20.03,51.96
484,485,"Navi Mumbai, India",29.41,9.72,31.29,20.53,73.30
485,486,"Pristina, Kosovo (Disputed Territory)",29.40,8.90,26.65,22.28,52.71
486,487,"Karachi, Pakistan",29.11,7.48,29.16,21.44,35.72
487,488,"Ahmedabad, India",28.95,6.65,31.25,21.09,57.06
488,489,"Chandigarh, India",28.94,6.31,30.74,19.97,64.70
489,490,"Chennai, India",28.78,7.09,31.45,18.75,71.99
490,491,"Goa, India",28.52,7.57,30.98,20.94,49.66
491,492,"Surat, India",28.47,4.50,30.17,21.43,55.55
492,493,"Kolkata, India",28.28,6.97,29.91,22.74,47.99
493,494,"Dnipropetrovsk, Ukraine",28.09,7.13,22.74,20.69,31.03
494,495,"Lucknow (Lakhnau), India",28.07,4.60,29.00,18.03,53.68
495,496,"Jaipur, India",27.92,4.62,29.81,16.61,65.05
496,497,"Kharkiv, Ukraine",27.85,9.94,22.03,19.26,22.54
497,498,"Vadodara, India",27.31,3.85,31.50,16.06,67.23
498,499,"Nagpur, India",27.18,4.86,29.35,19.34,68.56
499,500,"Indore, India",27.01,4.28,26.64,16.98,44.20
500,501,"Lviv, Ukraine",26.97,8.48,22.66,17.35,22.69
501,502,"Hyderabad, India",26.87,6.20,28.95,17.66,65.47
502,503,"Mysore, India",26.23,4.52,32.03,13.28,35.53
503,504,"Cairo, Egypt",26.19,5.14,23.30,22.47,23.96
504,505,"Visakhapatnam, India",25.57,5.14,28.40,16.13,53.78
505,506,"Kochi, India",25.40,6.18,28.26,14.41,60.04
506,507,"Bhubaneswar, India",25.24,4.57,28.87,14.71,52.38
507,508,"Coimbatore, India",24.83,5.61,26.31,15.29,47.01
508,509,"Alexandria, Egypt",24.54,5.09,23.50,17.66,21.42
509,510,"Mangalore, India",23.17,5.68,23.88,12.61,95.97
510,511,"Thiruvananthapuram, India",21.75,5.17,23.72,12.12,62.76

In [33]:
df["Total"]=np.nan
df

,Rank,City,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex,Total
0,1,"Zurich, Switzerland",149.53,66.76,163.71,140.58,126.30,NaN
1,2,"Hamilton, Bermuda",148.13,117.80,145.20,152.54,93.42,NaN
2,3,"Zug, Switzerland",142.54,67.39,148.36,143.18,105.62,NaN
3,4,"Geneva, Switzerland",142.12,70.25,147.13,138.96,115.20,NaN
4,5,"Basel, Switzerland",142.02,51.54,149.54,131.72,113.13,NaN
5,6,"Bern, Switzerland",135.51,45.33,145.72,122.48,101.65,NaN
6,7,"Lausanne, Switzerland",131.38,54.56,136.95,127.87,112.33,NaN
7,8,"Reykjavik, Iceland",130.73,55.90,128.37,140.61,68.49,NaN
8,9,"Lugano, Switzerland",124.39,51.73,120.83,127.53,108.92,NaN
9,10,"Stavanger, Norway",116.98,37.40,107.72,142.61,101.00,NaN
10,11,"Trondheim, Norway",116.02,41.27,110.10,128.03,93.68,NaN
11,12,"Oslo, Norway",114.78,47.99,111.48,126.20,86.67,NaN
12,13,"Bergen, Norway",112.66,39.58,106.84,117.45,87.68,NaN
13,14,"Nassau, Bahamas",109.58,37.40,103.09,99.27,43.82,NaN
14,15,"Honolulu, HI, United States",103.32,64.98,121.83,88.49,84.93,NaN
15,16,"San Francisco, CA, United States",101.94,119.63,116.73,93.57,104.40,NaN
16,17,"Anchorage, AK, United States",101.90,41.57,109.58,88.67,130.22,NaN
17,18,"Brooklyn, NY, United States",101.06,77.52,105.51,106.84,82.64,NaN
18,19,"New York, NY, United States",100.00,100.00,100.00,100.00,100.00,NaN
19,20,"Rockville, MD, United States",98.81,61.40,97.20,71.68,135.58,NaN
20,21,"Tokyo, Japan",97.71,38.68,107.25,57.87,93.49,NaN
21,22,"Copenhagen, Denmark",97.14,49.61,78.25,113.91,93.39,NaN
22,23,"Washington, DC, United States",95.96,74.32,96.97,90.78,107.86,NaN
23,24,"New Haven, CT, United States",94.10,47.09,112.78,91.54,114.53,NaN
24,25,"Berkeley, CA, United States",93.86,76.36,109.86,81.71,87.37,NaN
25,26,"Seattle, WA, United States",93.31,65.46,98.17,86.72,121.29,NaN
26,27,"Arlington, VA, United States",93.17,67.79,93.16,85.61,117.45,NaN
27,28,"Aalborg, Denmark",92.12,25.34,77.34,104.60,89.90,NaN
28,29,"Tel Aviv-Yafo, Israel",92.09,49.51,80.75,96.79,93.00,NaN
29,30,"Santa Rosa, CA, United States",91.92,55.04,97.22,78.70,116.21,NaN
...,...,...,...,...,...,...,...,...
481,482,"Bangalore, India",30.24,9.41,32.95,19.57,86.79,NaN
482,483,"Tunis, Tunisia",29.93,6.51,28.94,20.42,32.94,NaN
483,484,"Thane, India",29.83,8.51,31.74,20.03,51.96,NaN
484,485,"Navi Mumbai, India",29.41,9.72,31.29,20.53,73.30,NaN
485,486,"Pristina, Kosovo (Disputed Territory)",29.40,8.90,26.65,22.28,52.71,NaN
486,487,"Karachi, Pakistan",29.11,7.48,29.16,21.44,35.72,NaN
487,488,"Ahmedabad, India",28.95,6.65,31.25,21.09,57.06,NaN
488,489,"Chandigarh, India",28.94,6.31,30.74,19.97,64.70,NaN
489,490,"Chennai, India",28.78,7.09,31.45,18.75,71.99,NaN
490,491,"Goa, India",28.52,7.57,30.98,20.94,49.66,NaN
491,492,"Surat, India",28.47,4.50,30.17,21.43,55.55,NaN
492,493,"Kolkata, India",28.28,6.97,29.91,22.74,47.99,NaN
493,494,"Dnipropetrovsk, Ukraine",28.09,7.13,22.74,20.69,31.03,NaN
494,495,"Lucknow (Lakhnau), India",28.07,4.60,29.00,18.03,53.68,NaN
495,496,"Jaipur, India",27.92,4.62,29.81,16.61,65.05,NaN
496,497,"Kharkiv, Ukraine",27.85,9.94,22.03,19.26,22.54,NaN
497,498,"Vadodara, India",27.31,3.85,31.50,16.06,67.23,NaN
498,499,"Nagpur, India",27.18,4.86,29.35,19.34,68.56,NaN
499,500,"Indore, India",27.01,4.28,26.64,16.98,44.20,NaN
500,501,"Lviv, Ukraine",26.97,8.48,22.66,17.35,22.69,NaN
501,502,"Hyderabad, India",26.87,6.20,28.95,17.66,65.47,NaN
502,503,"Mysore, India",26.23,4.52,32.03,13.28,35.53,NaN
503,504,"Cairo, Egypt",26.19,5.14,23.30,22.47,23.96,NaN
504,505,"Visakhapatnam, India",25.57,5.14,28.40,16.13,53.78,NaN
505,506,"Kochi, India",25.40,6.18,28.26,14.41,60.04,NaN
506,507,"Bhubaneswar, India",25.24,4.57,28.87,14.71,52.38,NaN
507,508,"Coimbatore, India",24.83,5.61,26.31,15.29,47.01,NaN
508,509,"Alexandria, Egypt",24.54,5.09,23.50,17.66,21.42,NaN
509,510,"Mangalore, India",23.17,5.68,23.88,12.61,95.97,NaN
510,511,"Thiruvananthapuram, India",21.75,5.17,23.72,12.12,62.76,NaN

In [38]:
df[df["City"]=="Bhubaneswar, India"]

,Rank,City,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex,Total
506,507,"Bhubaneswar, India",25.24,4.57,28.87,14.71,52.38,NaN

In [39]:
df.to_csv("Work.csv")

In [45]:
del df['Rank']

In [46]:
df

,City,CostofLivingIndex,RentIndex,GroceriesIndex,RestaurantPriceIndex,LocalPurchasingPowerIndex
0,"Zurich, Switzerland",149.53,66.76,163.71,140.58,126.30
1,"Hamilton, Bermuda",148.13,117.80,145.20,152.54,93.42
2,"Zug, Switzerland",142.54,67.39,148.36,143.18,105.62
3,"Geneva, Switzerland",142.12,70.25,147.13,138.96,115.20
4,"Basel, Switzerland",142.02,51.54,149.54,131.72,113.13
5,"Bern, Switzerland",135.51,45.33,145.72,122.48,101.65
6,"Lausanne, Switzerland",131.38,54.56,136.95,127.87,112.33
7,"Reykjavik, Iceland",130.73,55.90,128.37,140.61,68.49
8,"Lugano, Switzerland",124.39,51.73,120.83,127.53,108.92
9,"Stavanger, Norway",116.98,37.40,107.72,142.61,101.00
10,"Trondheim, Norway",116.02,41.27,110.10,128.03,93.68
11,"Oslo, Norway",114.78,47.99,111.48,126.20,86.67
12,"Bergen, Norway",112.66,39.58,106.84,117.45,87.68
13,"Nassau, Bahamas",109.58,37.40,103.09,99.27,43.82
14,"Honolulu, HI, United States",103.32,64.98,121.83,88.49,84.93
15,"San Francisco, CA, United States",101.94,119.63,116.73,93.57,104.40
16,"Anchorage, AK, United States",101.90,41.57,109.58,88.67,130.22
17,"Brooklyn, NY, United States",101.06,77.52,105.51,106.84,82.64
18,"New York, NY, United States",100.00,100.00,100.00,100.00,100.00
19,"Rockville, MD, United States",98.81,61.40,97.20,71.68,135.58
20,"Tokyo, Japan",97.71,38.68,107.25,57.87,93.49
21,"Copenhagen, Denmark",97.14,49.61,78.25,113.91,93.39
22,"Washington, DC, United States",95.96,74.32,96.97,90.78,107.86
23,"New Haven, CT, United States",94.10,47.09,112.78,91.54,114.53
24,"Berkeley, CA, United States",93.86,76.36,109.86,81.71,87.37
25,"Seattle, WA, United States",93.31,65.46,98.17,86.72,121.29
26,"Arlington, VA, United States",93.17,67.79,93.16,85.61,117.45
27,"Aalborg, Denmark",92.12,25.34,77.34,104.60,89.90
28,"Tel Aviv-Yafo, Israel",92.09,49.51,80.75,96.79,93.00
29,"Santa Rosa, CA, United States",91.92,55.04,97.22,78.70,116.21
...,...,...,...,...,...,...
481,"Bangalore, India",30.24,9.41,32.95,19.57,86.79
482,"Tunis, Tunisia",29.93,6.51,28.94,20.42,32.94
483,"Thane, India",29.83,8.51,31.74,20.03,51.96
484,"Navi Mumbai, India",29.41,9.72,31.29,20.53,73.30
485,"Pristina, Kosovo (Disputed Territory)",29.40,8.90,26.65,22.28,52.71
486,"Karachi, Pakistan",29.11,7.48,29.16,21.44,35.72
487,"Ahmedabad, India",28.95,6.65,31.25,21.09,57.06
488,"Chandigarh, India",28.94,6.31,30.74,19.97,64.70
489,"Chennai, India",28.78,7.09,31.45,18.75,71.99
490,"Goa, India",28.52,7.57,30.98,20.94,49.66
491,"Surat, India",28.47,4.50,30.17,21.43,55.55
492,"Kolkata, India",28.28,6.97,29.91,22.74,47.99
493,"Dnipropetrovsk, Ukraine",28.09,7.13,22.74,20.69,31.03
494,"Lucknow (Lakhnau), India",28.07,4.60,29.00,18.03,53.68
495,"Jaipur, India",27.92,4.62,29.81,16.61,65.05
496,"Kharkiv, Ukraine",27.85,9.94,22.03,19.26,22.54
497,"Vadodara, India",27.31,3.85,31.50,16.06,67.23
498,"Nagpur, India",27.18,4.86,29.35,19.34,68.56
499,"Indore, India",27.01,4.28,26.64,16.98,44.20
500,"Lviv, Ukraine",26.97,8.48,22.66,17.35,22.69
501,"Hyderabad, India",26.87,6.20,28.95,17.66,65.47
502,"Mysore, India",26.23,4.52,32.03,13.28,35.53
503,"Cairo, Egypt",26.19,5.14,23.30,22.47,23.96
504,"Visakhapatnam, India",25.57,5.14,28.40,16.13,53.78
505,"Kochi, India",25.40,6.18,28.26,14.41,60.04
506,"Bhubaneswar, India",25.24,4.57,28.87,14.71,52.38
507,"Coimbatore, India",24.83,5.61,26.31,15.29,47.01
508,"Alexandria, Egypt",24.54,5.09,23.50,17.66,21.42
509,"Mangalore, India",23.17,5.68,23.88,12.61,95.97
510,"Thiruvananthapuram, India",21.75,5.17,23.72,12.12,62.76

In [50]:
for c in df.columns:
    print ("---- %s ---" % c)
    print( df[c].value_counts())

---- City ---
Dar Es Salaam, Tanzania                1
Limerick, Ireland                      1
Indore, India                          1
Chandigarh, India                      1
Wellington, New Zealand                1
Noida, India                           1
Madrid, Spain                          1
Porto, Portugal                        1
Dayton, OH, United States              1
Antwerp, Belgium                       1
Moncton, Canada                        1
Hobart, Australia                      1
Ahmedabad, India                       1
Haifa, Israel                          1
Doha, Qatar                            1
Lethbridge, AB, Canada                 1
Ann Arbor, MI, United States           1
Gainesville, FL, United States         1
Barcelona, Spain                       1
Allentown, PA, United States           1
Tampere, Finland                       1
Algiers, Algeria                       1
Kitchener, Canada                      1
Gold Coast, Australia                  1
Sharjah, United Arab Emirates          1
Oxford, United Kingdom                 1
San Salvador, El Salvador              1
Guangzhou, China                       1
Newcastle Upon Tyne, United Kingdom    1
Hartford, CT, United States            1
                                      ..
Coimbatore, India                      1
Manama, Bahrain                        1
Beijing, China                         1
Cordoba, Argentina                     1
Athens, Greece                         1
Riga, Latvia                           1
Nuremberg, Germany                     1
Rabat, Morocco                         1
Reading, United Kingdom                1
Gothenburg, Sweden                     1
Dhaka, Bangladesh                      1
Bratislava, Slovakia                   1
Santiago, Chile                        1
Adelaide, Australia                    1
Cancun, Mexico                         1
Copenhagen, Denmark                    1
Las Vegas, NV, United States           1
Singapore, Singapore                   1
Kota Kinabalu, Malaysia                1
Mexico City, Mexico                    1
Melbourne, Australia                   1
Birmingham, United Kingdom             1
Santo Domingo, Dominican Republic      1
Tulsa, OK, United States               1
Hamilton, Canada                       1
Houston, TX, United States             1
Pittsburgh, PA, United States          1
Thiruvananthapuram, India              1
Durham, NC, United States              1
Bonn, Germany                          1
Name: City, dtype: int64
---- CostofLivingIndex ---
79.24    3
71.41    2
73.02    2
80.70    2
83.15    2
57.26    2
42.58    2
84.43    2
75.98    2
81.71    2
62.75    2
47.02    2
90.73    2
72.08    2
72.88    2
79.48    2
71.94    2
80.82    2
76.43    2
82.76    2
74.95    2
76.74    1
74.52    1
52.16    1
93.17    1
80.22    1
78.55    1
66.58    1
71.45    1
38.57    1
        ..
77.53    1
72.36    1
72.77    1
82.49    1
48.10    1
44.39    1
88.25    1
40.77    1
73.64    1
67.57    1
39.43    1
66.86    1
41.13    1
74.60    1
69.94    1
75.20    1
68.40    1
36.75    1
36.46    1
36.15    1
67.35    1
71.37    1
91.18    1
70.42    1
70.11    1
70.68    1
73.99    1
66.65    1
50.86    1
87.43    1
Name: CostofLivingIndex, dtype: int64
---- RentIndex ---
29.56    2
11.76    2
18.60    2
12.91    2
6.77     2
37.05    2
36.74    2
37.40    2
12.80    2
31.71    2
21.77    2
9.10     2
8.53     2
11.33    2
21.85    2
35.04    2
27.45    2
24.87    2
16.94    2
20.20    2
15.34    2
6.00     2
34.29    2
12.07    2
10.55    2
5.14     2
31.26    1
17.05    1
28.30    1
15.10    1
        ..
7.97     1
4.57     1
65.60    1
67.55    1
14.16    1
4.61     1
23.88    1
8.60     1
34.60    1
9.87     1
40.14    1
28.16    1
12.09    1
67.79    1
4.52     1
5.61     1
66.76    1
35.94    1
18.32    1
27.14    1
24.54    1
24.76    1
11.99    1
25.68    1
15.39    1
68.70    1
36.99    1
25.26    1
20.33    1
3.13     1
Name: RentIndex, dtype: int64
---- GroceriesIndex ---
51.25     2
90.72     2
67.21     2
90.68     2
67.30     2
67.70     2
60.84     2
46.75     2
31.56     2
73.27     2
70.54     2
38.81     2
36.48     2
70.26     2
87.30     2
80.92     2
49.35     1
76.12     1
30.52     1
37.50     1
31.65     1
56.00     1
47.94     1
91.14     1
76.30     1
75.05     1
32.47     1
39.62     1
70.07     1
145.72    1
         ..
69.13     1
74.43     1
80.05     1
74.15     1
46.85     1
69.55     1
97.22     1
68.09     1
36.13     1
33.80     1
36.32     1
81.20     1
67.26     1
71.95     1
96.04     1
70.52     1
39.14     1
70.80     1
73.09     1
66.41     1
50.76     1
82.87     1
72.61     1
72.84     1
77.57     1
67.13     1
47.22     1
75.74     1
83.48     1
68.10     1
Name: GroceriesIndex, dtype: int64
---- RestaurantPriceIndex ---
68.17     2
82.37     2
30.56     2
29.58     2
72.53     2
32.57     2
65.61     2
86.72     2
71.67     2
39.34     2
29.30     2
62.51     2
27.72     2
78.70     2
28.29     2
32.16     2
17.66     2
32.72     2
14.41     1
22.28     1
31.73     1
77.84     1
75.54     1
27.68     1
38.31     1
15.29     1
74.27     1
140.61    1
28.99     1
68.51     1
         ..
20.94     1
14.71     1
65.50     1
65.84     1
65.58     1
65.67     1
64.70     1
65.37     1
65.95     1
65.40     1
88.67     1
65.63     1
28.77     1
67.22     1
65.89     1
65.86     1
25.13     1
66.97     1
65.94     1
35.12     1
65.45     1
65.82     1
24.15     1
65.70     1
65.65     1
69.05     1
25.30     1
68.49     1
36.03     1
68.96     1
Name: RestaurantPriceIndex, dtype: int64
---- LocalPurchasingPowerIndex ---
29.91     2
93.39     2
95.70     2
67.23     2
39.66     2
101.65    2
84.89     2
34.58     2
102.14    2
59.73     2
108.18    2
29.97     2
63.35     2
96.37     2
133.67    1
13.03     1
95.97     1
23.20     1
98.66     1
135.53    1
136.03    1
72.70     1
28.14     1
24.21     1
140.69    1
74.38     1
22.54     1
27.77     1
137.36    1
25.99     1
         ..
72.13     1
82.09     1
35.53     1
95.40     1
23.96     1
64.23     1
34.68     1
102.52    1
104.97    1
94.42     1
39.29     1
66.12     1
35.10     1
110.98    1
69.81     1
101.00    1
116.64    1
97.14     1
68.39     1
36.85     1
56.32     1
89.06     1
67.12     1
71.17     1
96.80     1
70.25     1
106.15    1
73.51     1
66.49     1
2.96      1
Name: LocalPurchasingPowerIndex, dtype: int64

In [51]:
df1 = pd.read_csv("Telco-Customer-Churn.csv")

In [52]:
df1

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,1
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,0
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,0
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0
10,9763-GRSKD,Male,0,Yes,Yes,13,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,49.95,587.45,0
11,7469-LKBCI,Male,0,No,No,16,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),18.95,326.8,0
12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,0
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,1
14,5129-JLPIS,Male,0,No,No,25,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05,0
15,3655-SNQYZ,Female,0,Yes,Yes,69,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),113.25,7895.15,0
16,8191-XWSZG,Female,0,No,No,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.65,1022.95,0
17,9959-WOFKT,Male,0,No,Yes,71,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),106.70,7382.25,0
18,4190-MFLUW,Female,0,Yes,Yes,10,Yes,No,DSL,No,...,Yes,Yes,No,No,Month-to-month,No,Credit card (automatic),55.20,528.35,1
19,4183-MYFRB,Female,0,No,No,21,Yes,No,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,90.05,1862.9,0
20,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,1
21,1680-VDCWW,Male,0,Yes,No,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),19.80,202.25,0
22,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,1
23,3638-WEABW,Female,0,Yes,No,58,Yes,Yes,DSL,No,...,No,Yes,No,No,Two year,Yes,Credit card (automatic),59.90,3505.1,0
24,6322-HRPFA,Male,0,Yes,Yes,49,Yes,No,DSL,Yes,...,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.60,2970.3,0
25,6865-JZNKO,Female,0,No,No,30,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.6,0
26,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.35,4749.15,1
27,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,30.20,30.2,1
28,5248-YGIJN,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),90.25,6369.45,0
29,8773-HHUOZ,Female,0,No,Yes,17,Yes,No,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,64.70,1093.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5755,5937-EORGB,Male,1,Yes,No,15,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Electronic check,96.50,1392.25,0
5756,6349-JDHQP,Female,0,No,No,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.85,1049.6,0
5757,5539-HIVAK,Female,1,Yes,No,28,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,25.70,734.6,0
5758,5847-MXBEO,Male,0,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.30,475.1,0
5759,9985-MWVIX,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.15,70.15,1
5760,4583-PARNH,Male,1,Yes,No,16,Yes,No,Fiber optic,No,...,Yes,Yes,No,Yes,Month-to-month,Yes,Electronic check,91.55,1540.05,0
5761,1116-FRYVH,Female,0,Yes,Yes,48,No,No phone service,DSL,Yes,...,No,Yes,No,No,Two year,No,Mailed check,39.40,1978.65,0
5762,1421-HCERK,Male,1,Yes,No,30,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,No,Month-to-month,Yes,Bank transfer (automatic),105.70,3181.8,0
5763,9633-XQABV,Female,0,No,No,3,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.25,229.7,0
5764,0716-BQNDX,Male,1,No,No,57,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,Yes,Two year,No,Electronic check,93.75,5625.55,0
5765,1265-XTECC,Female,1,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,One year,Yes,Credit card (automatic),96.55,6581.9,1
5766,1183-CANVH,Female,0,Yes,No,23,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,No,Bank transfer (automatic),60.00,1347.15,0
5767,1972-XMUWV,Female,0,Yes,No,65,Yes,No,DSL,No,...,No,Yes,Yes,No,Two year,Yes,Credit card (automatic),59.80,3808.2,0
5768,8679-LZBMD,Male,0,Yes,No,44,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,One year,Yes,Bank transfer (automatic),90.65,3974.15,0
5769,3407-JMJQQ,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),109.00,7661.8,0
5770,6252-DFGTK,Female,0,Yes,No,37,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,One year,No,Credit card (automatic),68.10,2479.25,0
5771,1539-LNKHM,Female,0,No,No,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.40,266.6,0
5772,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.4,0
5773,0289-IVARM,Female,0,No,No,35,Yes,No,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Electronic check,60.55,1982.6,0
5774,9761-XUJWD,Male,0,No,No,5,Yes,No,DSL,No,...,No,Yes,No,Yes,Month-to-month,Yes,Bank transfer (automatic),65.60,339.9,0
5775,4057-FKCZK,Male,0,Yes,Yes,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Two year,No,Bank transfer (automatic),82.50,4828.05,0
5776,4291-TPNFG,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,No,Yes,Two year,Yes,Bank transfer (automatic),82.30,5980.55,0
5777,6087-YPWHO,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,Two year,No,Mailed check,68.15,4808.7,0
5778,3090-QFUVD,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Credit card (automatic),20.30,20.3,0
5779,2237-ZFSMY,Female,0,No,No,39,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,No,One year,Yes,Electronic check,95.55,3692.85,1
5780,1722-LDZJS,Male,0,Yes,Yes,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),20.20,1068.15,0
5781,1818-ESQMW,Female,0,No,No,27,Yes,No,Fiber optic,No,...,Yes,Yes,No,Yes,Month-to-month,Yes,Electronic check,89.20,2383.6,0
5782,4871-JTKJF,Female,1,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.65,69.65,1
5783,1415-YFWLT,Female,1,No,No,1,Yes,No,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,89.30,89.3,1
5784,7401-RUBNK,Female,0,Yes,No,18,Yes,No,Fiber optic,Yes,...,No,No,No,No,Month-to-month,No,Electronic check,74.80,1438.05,0

In [54]:
for c in df1.columns:
    print ("---- %s ---" % c)
    print( df1[c].value_counts())

---- customerID ---
6303-KFWSL    1
5688-KZTSN    1
7181-BQYBV    1
2472-OVKUP    1
4553-DVPZG    1
3976-NLDEZ    1
9526-JAWYF    1
1337-BOZWO    1
5133-VRSAB    1
3913-FCUUW    1
4647-MUZON    1
0461-CVKMU    1
0536-ESJEP    1
3086-RUCRN    1
8780-IXSTS    1
5649-ANRML    1
8096-LOIST    1
8060-HIWJJ    1
5176-LMJXE    1
6559-ILWKJ    1
4654-ULTTN    1
5848-FHRFC    1
0278-YXOOG    1
0442-ZXKVS    1
4088-YLDSU    1
9970-QBCDA    1
1845-CSBRZ    1
0078-XZMHT    1
0396-YCHWO    1
8871-JLMHM    1
             ..
2665-NPTGL    1
5732-IKGQH    1
0365-GXEZS    1
1569-TTNYJ    1
3617-XLSGQ    1
9588-OZDMQ    1
4565-EVZMJ    1
1088-CNNKB    1
8234-GSZYK    1
3898-GUYTS    1
8259-DZLIZ    1
0541-FITGH    1
3466-BYAVD    1
7244-KXYZN    1
3511-APPBJ    1
5868-YTYKS    1
9938-ZREHM    1
3082-VQXNH    1
6178-KFNHS    1
6627-CFOSN    1
3793-MMFUH    1
4804-NCPET    1
9029-FEGVJ    1
8229-MYEJZ    1
5266-PFRQK    1
5394-MEITZ    1
1897-RCFUM    1
4203-QGNZA    1
6968-GMKPR    1
2577-GVSIL    1
Name: customerID, dtype: int64
---- gender ---
Male      2918
Female    2867
Name: gender, dtype: int64
---- SeniorCitizen ---
0    4848
1     937
Name: SeniorCitizen, dtype: int64
---- Partner ---
No     2984
Yes    2801
Name: Partner, dtype: int64
---- Dependents ---
No     4071
Yes    1714
Name: Dependents, dtype: int64
---- tenure ---
1     511
72    305
2     197
3     156
4     147
71    146
7     117
5     109
8     106
10     99
12     98
9      97
70     94
11     86
68     83
24     82
6      82
18     80
69     79
15     79
13     78
22     78
66     77
17     74
67     73
23     71
56     70
16     69
35     66
65     66
     ...
53     58
27     57
51     57
41     57
19     57
50     56
34     55
47     55
33     55
37     55
31     54
58     54
49     54
55     53
40     53
62     53
42     52
45     52
21     51
54     51
28     50
43     50
48     49
57     49
39     46
38     45
59     44
44     40
36     38
0       9
Name: tenure, dtype: int64
---- PhoneService ---
Yes    5253
No      532
Name: PhoneService, dtype: int64
---- MultipleLines ---
No                  2804
Yes                 2449
No phone service     532
Name: MultipleLines, dtype: int64
---- InternetService ---
Fiber optic    2543
DSL            1974
No             1268
Name: InternetService, dtype: int64
---- OnlineSecurity ---
No                     2855
Yes                    1662
No internet service    1268
Name: OnlineSecurity, dtype: int64
---- OnlineBackup ---
No                     2533
Yes                    1984
No internet service    1268
Name: OnlineBackup, dtype: int64
---- DeviceProtection ---
No                     2526
Yes                    1991
No internet service    1268
Name: DeviceProtection, dtype: int64
---- TechSupport ---
No                     2850
Yes                    1667
No internet service    1268
Name: TechSupport, dtype: int64
---- StreamingTV ---
No                     2296
Yes                    2221
No internet service    1268
Name: StreamingTV, dtype: int64
---- StreamingMovies ---
No                     2279
Yes                    2238
No internet service    1268
Name: StreamingMovies, dtype: int64
---- Contract ---
Month-to-month    3198
Two year          1384
One year          1203
Name: Contract, dtype: int64
---- PaperlessBilling ---
Yes    3418
No     2367
Name: PaperlessBilling, dtype: int64
---- PaymentMethod ---
Electronic check             1939
Mailed check                 1321
Bank transfer (automatic)    1274
Credit card (automatic)      1251
Name: PaymentMethod, dtype: int64
---- MonthlyCharges ---
20.05     45
19.85     41
19.90     38
20.00     38
19.70     37
19.95     36
20.15     35
20.25     35
19.80     33
19.75     32
19.65     32
20.10     31
19.55     31
19.60     30
20.45     28
20.35     28
20.40     27
20.20     26
19.40     26
19.45     25
20.55     24
19.50     24
20.30     23
20.50     22
19.35     20
19.30     20
20.65     19
25.25     18
20.75     16
25.10     16
          ..
63.05      1
81.65      1
85.85      1
53.55      1
48.25      1
115.00     1
35.35      1
57.65      1
73.30      1
60.75      1
73.20      1
35.70      1
114.75     1
31.65      1
111.75     1
76.80      1
102.15     1
42.60      1
103.00     1
72.45      1
72.35      1
65.90      1
113.75     1
58.00      1
31.20      1
77.30      1
33.15      1
30.45      1
52.00      1
41.35      1
Name: MonthlyCharges, dtype: int64
---- TotalCharges ---
           9
19.75      9
20.2       9
19.65      7
20.05      7
19.45      6
20.15      6
19.9       6
19.55      5
45.3       5
20.45      5
20.25      5
19.5       4
74.7       4
75.3       4
70.6       4
50.15      4
19.85      4
19.2       4
69.55      3
44.4       3
84.5       3
69.95      3
20.55      3
50.75      3
86.05      3
69.6       3
49.9       3
70.45      3
44.75      3
          ..
2337.45    1
4134.85    1
888.65     1
4145.9     1
129.2      1
6733       1
1529.45    1
1249.25    1
170.85     1
4698.05    1
655.3      1
2117.2     1
1975.85    1
2586       1
73.45      1
452.7      1
4029.95    1
4424.2     1
544.55     1
2628.6     1
617.15     1
765.5      1
332.5      1
21         1
5680.9     1
199.85     1
1539.75    1
5794.45    1
268.4      1
754        1
Name: TotalCharges, dtype: int64
---- Churn ---
0    4258
1    1527
Name: Churn, dtype: int64

In [55]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5785 entries, 0 to 5784
Data columns (total 21 columns):
customerID          5785 non-null object
gender              5785 non-null object
SeniorCitizen       5785 non-null int64
Partner             5785 non-null object
Dependents          5785 non-null object
tenure              5785 non-null int64
PhoneService        5785 non-null object
MultipleLines       5785 non-null object
InternetService     5785 non-null object
OnlineSecurity      5785 non-null object
OnlineBackup        5785 non-null object
DeviceProtection    5785 non-null object
TechSupport         5785 non-null object
StreamingTV         5785 non-null object
StreamingMovies     5785 non-null object
Contract            5785 non-null object
PaperlessBilling    5785 non-null object
PaymentMethod       5785 non-null object
MonthlyCharges      5785 non-null float64
TotalCharges        5785 non-null object
Churn               5785 non-null int64
dtypes: float64(1), int64(3), object(17)
memory usage: 949.2+ KB

In [56]:
df1.describe()

       SeniorCitizen       tenure  MonthlyCharges        Churn
count    5785.000000  5785.000000     5785.000000  5785.000000
mean        0.161971    32.263786       64.781011     0.263959
std         0.368456    24.584428       30.116348     0.440815
min         0.000000     0.000000       18.250000     0.000000
25%         0.000000     9.000000       35.450000     0.000000
50%         0.000000    29.000000       70.400000     0.000000
75%         0.000000    55.000000       89.850000     1.000000
max         1.000000    72.000000      118.750000     1.000000

In [58]:
null = df1.columns[df1.isnull().any()]
df1[null].isnull().sum()

Series([], dtype: float64)

In [59]:
print(df1[df1["TotalCharges"].isnull()][null])

Empty DataFrame
Columns: []
Index: []

In [62]:
print(df1[df1.isnull().any(axis=1)][null].head())

Empty DataFrame
Columns: []
Index: []

In [63]:
pd.isnull("df1")

False

In [68]:
df1[df1["tenure"]>50]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0
12,8091-TTVAX,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1,0
15,3655-SNQYZ,Female,0,Yes,Yes,69,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),113.25,7895.15,0
16,8191-XWSZG,Female,0,No,No,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.65,1022.95,0
17,9959-WOFKT,Male,0,No,Yes,71,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),106.70,7382.25,0
23,3638-WEABW,Female,0,Yes,No,58,Yes,Yes,DSL,No,...,No,Yes,No,No,Two year,Yes,Credit card (automatic),59.90,3505.1,0
28,5248-YGIJN,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),90.25,6369.45,0
30,3841-NFECX,Female,1,Yes,No,71,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,No,No,Two year,Yes,Credit card (automatic),96.35,6766.95,0
35,6234-RAAPL,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,No,Yes,Yes,No,Two year,No,Bank transfer (automatic),99.90,7251.7,0
41,9489-DEDVP,Female,0,Yes,Yes,70,Yes,Yes,DSL,Yes,...,No,No,Yes,No,Two year,Yes,Credit card (automatic),69.20,4872.35,0
43,4671-VJLCL,Female,0,No,No,63,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Credit card (automatic),79.85,4861.45,0
48,7639-LIAYI,Male,0,No,No,52,Yes,Yes,DSL,Yes,...,No,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),79.75,4217.8,0
49,2954-PIBKO,Female,0,Yes,Yes,69,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,Two year,Yes,Credit card (automatic),64.15,4254.1,0
54,4667-QONEA,Female,1,Yes,Yes,60,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,One year,Yes,Credit card (automatic),74.85,4456.35,0
56,8769-KKTPH,Female,0,Yes,Yes,63,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,One year,Yes,Credit card (automatic),99.65,6311.2,0
57,5067-XJQFU,Male,1,Yes,Yes,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,108.45,7076.35,0
59,5954-BDFSG,Female,0,No,No,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),107.50,7853.7,0
61,1215-FIGMP,Male,0,No,No,60,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),89.90,5450.7,0
62,0526-SXDJP,Male,0,Yes,No,72,No,No phone service,DSL,Yes,...,Yes,No,No,No,Two year,No,Bank transfer (automatic),42.10,2962,0
71,0731-EBJQB,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Electronic check,20.40,1090.65,0
72,1891-QRQSA,Male,1,Yes,Yes,64,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),111.60,7099,0
73,8028-PNXHQ,Male,0,Yes,Yes,62,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),24.25,1424.6,0
75,2673-CXQEU,Female,1,No,No,56,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,One year,No,Electronic check,110.50,6139.5,0
92,7233-PAHHL,Male,0,Yes,Yes,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,84.00,5714.25,0
93,6067-NGCEU,Female,0,No,No,65,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),111.05,7107,0
94,9848-JQJTX,Male,0,No,No,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),100.90,7459.05,0
96,9803-FTJCG,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,...,No,Yes,No,No,One year,Yes,Credit card (automatic),66.85,4748.7,0
98,3212-KXOCR,Male,0,No,No,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),21.00,1107.2,0
103,5386-THSLQ,Female,1,Yes,No,66,No,No phone service,DSL,No,...,Yes,No,Yes,No,One year,No,Bank transfer (automatic),45.55,3027.25,0
104,3192-NQECA,Male,0,Yes,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),110.00,7611.85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5684,0193-ESZXP,Female,1,Yes,No,58,Yes,No,Fiber optic,Yes,...,No,Yes,Yes,Yes,One year,Yes,Credit card (automatic),105.50,6205.5,1
5690,0336-KXKFK,Male,0,No,No,72,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),61.20,4390.25,0
5693,5327-XOKKY,Male,1,Yes,No,72,Yes,Yes,DSL,No,...,Yes,No,Yes,Yes,Two year,Yes,Credit card (automatic),73.45,5329,0
5695,1813-JYWTO,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,No,No,No,No,Two year,No,Bank transfer (automatic),80.45,5737.6,0
5697,1984-FCOWB,Female,0,Yes,No,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,109.50,7674.55,1
5702,5287-QWLKY,Male,1,Yes,Yes,71,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),105.10,7548.1,1
5703,0795-XCCTE,Male,1,No,No,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),25.40,1809.35,0
5710,6297-NOOPG,Female,0,Yes,No,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,110.50,7752.05,0
5717,8169-SAEJD,Male,1,Yes,No,69,No,No phone service,DSL,Yes,...,No,No,Yes,Yes,Two year,No,Credit card (automatic),56.55,3952.65,0
5723,7824-PANSQ,Male,0,No,No,58,Yes,Yes,Fiber optic,No,...,No,Yes,No,No,Month-to-month,No,Bank transfer (automatic),80.65,4807.35,0
5727,8707-HOEDG,Female,0,Yes,Yes,70,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,110.20,7689.8,0
5730,7167-PCEYD,Male,0,No,No,67,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,19.80,1311.3,0
5733,4817-KEQSP,Female,0,Yes,Yes,71,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.85,1326.35,0
5734,6408-WHTEF,Male,0,Yes,Yes,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,89.40,6376.55,0
5739,4199-QHJNM,Male,1,Yes,No,67,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),102.90,6989.7,0
5740,8882-TLVRW,Male,0,Yes,Yes,69,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,Two year,No,Mailed check,39.10,2779.5,0
5742,5135-GRQJV,Male,1,Yes,No,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,114.50,8331.95,0
5745,3580-GICBM,Female,0,Yes,Yes,61,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,24.20,1445.2,0
5749,3349-ANQNH,Female,1,No,No,59,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Electronic check,99.50,5890,0
5752,7480-SPLEF,Male,0,Yes,Yes,69,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),26.00,1796.55,0
5756,6349-JDHQP,Female,0,No,No,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.85,1049.6,0
5764,0716-BQNDX,Male,1,No,No,57,Yes,Yes,Fiber optic,Yes,...,No,Yes,No,Yes,Two year,No,Electronic check,93.75,5625.55,0
5765,1265-XTECC,Female,1,Yes,No,68,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,One year,Yes,Credit card (automatic),96.55,6581.9,1
5767,1972-XMUWV,Female,0,Yes,No,65,Yes,No,DSL,No,...,No,Yes,Yes,No,Two year,Yes,Credit card (automatic),59.80,3808.2,0
5769,3407-JMJQQ,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,Yes,Two year,Yes,Bank transfer (automatic),109.00,7661.8,0
5772,8645-KOMJQ,Male,0,Yes,Yes,69,Yes,Yes,DSL,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),81.95,5601.4,0
5775,4057-FKCZK,Male,0,Yes,Yes,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Two year,No,Bank transfer (automatic),82.50,4828.05,0
5776,4291-TPNFG,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,No,Yes,Two year,Yes,Bank transfer (automatic),82.30,5980.55,0
5777,6087-YPWHO,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,No,No,Two year,No,Mailed check,68.15,4808.7,0
5780,1722-LDZJS,Male,0,Yes,Yes,53,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),20.20,1068.15,0